### ISSUE TITLE
No sensor data with 2021.9.1

### ISSUE THREAD

**Issue by Crayjin** [carstenschroeder/elv_ws980wifi#3]
Cannot retrieve any data from the sensors since HA 2021.9.0. (No improvement with 2021.9.1)

Any breaking changes requiring adaptations?

![image](https://user-images.githubusercontent.com/24563614/131953323-7902992e-9126-402f-adea-7eb5074bb4da.png)

Regarding the connection: WeatherStation is still reachable on the same IP and also reachable via WeatherSmartIP Windows app.

I could find some log errors:

> This error originated from a custom integration.
> 
> Logger: custom_components.elv_ws980wifi
> Source: custom_components/elv_ws980wifi/__init__.py:240
> Integration: ELV WS980Wifi custom integration (documentation)
> First occurred: 1:00:45 PM (10 occurrences)
> Last logged: 4:18:36 PM
> 
> timed out

> This error originated from a custom integration.
> 
> Logger: custom_components.elv_ws980wifi
> Source: custom_components/elv_ws980wifi/__init__.py:111
> Integration: ELV WS980Wifi custom integration (documentation)
> First occurred: 1:00:45 PM (14 occurrences)
> Last logged: 4:19:02 PM
> 
> Connection error
> Network error

> 2021-09-03 11:00:45 ERROR (SyncWorker_15) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:00:45 ERROR (SyncWorker_15) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:01:05 ERROR (SyncWorker_14) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:01:05 ERROR (SyncWorker_14) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:01:45 ERROR (SyncWorker_6) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:01:45 ERROR (SyncWorker_6) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:02:25 ERROR (SyncWorker_0) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:02:25 ERROR (SyncWorker_0) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:02:45 ERROR (SyncWorker_17) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:02:45 ERROR (SyncWorker_17) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:03:25 ERROR (SyncWorker_12) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:03:25 ERROR (SyncWorker_12) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:03:45 ERROR (SyncWorker_0) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:03:45 ERROR (SyncWorker_0) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:04:05 ERROR (SyncWorker_5) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:04:05 ERROR (SyncWorker_5) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 11:04:25 ERROR (SyncWorker_10) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 11:04:25 ERROR (SyncWorker_10) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 12:54:05 ERROR (SyncWorker_19) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 12:54:05 ERROR (SyncWorker_19) [custom_components.elv_ws980wifi] Network error
> 2021-09-03 13:25:01 ERROR (SyncWorker_4) [custom_components.elv_ws980wifi] index out of range
> 2021-09-03 13:25:01 ERROR (SyncWorker_4) [custom_components.elv_ws980wifi] Network error
> 2021-09-03 13:56:01 ERROR (SyncWorker_2) [custom_components.elv_ws980wifi] index out of range
> 2021-09-03 13:56:01 ERROR (SyncWorker_2) [custom_components.elv_ws980wifi] Network error
> 2021-09-03 14:18:36 ERROR (SyncWorker_2) [custom_components.elv_ws980wifi] timed out
> 2021-09-03 14:18:36 ERROR (SyncWorker_2) [custom_components.elv_ws980wifi] Connection error
> 2021-09-03 14:19:02 ERROR (SyncWorker_8) [custom_components.elv_ws980wifi] index out of range
> 2021-09-03 14:19:02 ERROR (SyncWorker_8) [custom_components.elv_ws980wifi] Network error
> 2021-09-03 14:37:51 ERROR (SyncWorker_16) [custom_components.elv_ws980wifi] Checksum mismatch
> 2021-09-03 14:37:51 ERROR (SyncWorker_16) [custom_components.elv_ws980wifi] Checksum error

**Comment by Crayjin** [comment]
@carstenschroeder Thanks for working on the adaptation already. Just uploaded the current state of your feature branch (for_2019.0) to my HASS instance and values are showing up again.

**Comment by carstenschroeder** [comment]
@Crayjin thanks for testing :) I will merge the changes shortly.
